/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import sql.CrudCamiones;

/**
 *
 * @author Esteban Ramos Martínez
 */
public class Camiones extends javax.swing.JPanel {

    CrudCamiones cc = new CrudCamiones();

    /**
     * Creates new form Camiones
     */
    public Camiones() {
        initComponents();
        cc.mostrarCamiones(tablaCamiones);
        ocultarColumnas(tablaCamiones, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCamiones = new javax.swing.JTable();
        jchofer = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        Text5 = new javax.swing.JLabel();
        jmodelo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        jchapa = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        panelAddCamion = new javax.swing.JPanel();
        btn_AddCamion = new javax.swing.JLabel();
        panelDelCamion = new javax.swing.JPanel();
        btn_DelCamion = new javax.swing.JLabel();
        panelUpdateCamion = new javax.swing.JPanel();
        btn_UpdateCamion = new javax.swing.JLabel();
        jbuscar = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        search1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCamiones.setBackground(new java.awt.Color(255, 255, 255));
        tablaCamiones.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaCamiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Chapa", "Modelo", "Chofer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCamiones.getTableHeader().setReorderingAllowed(false);
        tablaCamiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCamionesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaCamionesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCamiones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 180));

        jchofer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jchofer.setForeground(new java.awt.Color(102, 102, 102));
        jchofer.setBorder(null);
        jchofer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jchoferMousePressed(evt);
            }
        });
        jchofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchoferActionPerformed(evt);
            }
        });
        jchofer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jchoferKeyTyped(evt);
            }
        });
        add(jchofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 220, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 220, 10));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Chofer");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jmodelo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmodelo.setForeground(new java.awt.Color(102, 102, 102));
        jmodelo.setBorder(null);
        jmodelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmodeloMousePressed(evt);
            }
        });
        jmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodeloActionPerformed(evt);
            }
        });
        add(jmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 220, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 220, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Modelo");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jchapa.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jchapa.setForeground(new java.awt.Color(102, 102, 102));
        jchapa.setBorder(null);
        jchapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jchapaMousePressed(evt);
            }
        });
        jchapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchapaActionPerformed(evt);
            }
        });
        jchapa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jchapaKeyTyped(evt);
            }
        });
        add(jchapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 220, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Chapa");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        panelAddCamion.setBackground(new java.awt.Color(18, 90, 173));
        panelAddCamion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelAddCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddCamionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAddCamionMousePressed(evt);
            }
        });
        panelAddCamion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_AddCamion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_AddCamion.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddCamion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_AddCamion.setText("Agregar");
        btn_AddCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AddCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AddCamionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AddCamionMousePressed(evt);
            }
        });
        panelAddCamion.add(btn_AddCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        add(panelAddCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 90, -1));

        panelDelCamion.setBackground(new java.awt.Color(18, 90, 173));
        panelDelCamion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelDelCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDelCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDelCamionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelDelCamionMousePressed(evt);
            }
        });
        panelDelCamion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_DelCamion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_DelCamion.setForeground(new java.awt.Color(255, 255, 255));
        btn_DelCamion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_DelCamion.setText("Borrar");
        btn_DelCamion.setEnabled(false);
        btn_DelCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DelCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DelCamionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DelCamionMousePressed(evt);
            }
        });
        panelDelCamion.add(btn_DelCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        add(panelDelCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, -1));

        panelUpdateCamion.setBackground(new java.awt.Color(18, 90, 173));
        panelUpdateCamion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelUpdateCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUpdateCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUpdateCamionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelUpdateCamionMousePressed(evt);
            }
        });
        panelUpdateCamion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_UpdateCamion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_UpdateCamion.setForeground(new java.awt.Color(255, 255, 255));
        btn_UpdateCamion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_UpdateCamion.setText("Editar");
        btn_UpdateCamion.setEnabled(false);
        btn_UpdateCamion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_UpdateCamionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_UpdateCamionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_UpdateCamionMousePressed(evt);
            }
        });
        panelUpdateCamion.add(btn_UpdateCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        add(panelUpdateCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jbuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jbuscar.setForeground(new java.awt.Color(102, 102, 102));
        jbuscar.setText("Ingrese la chapa del camión a buscar");
        jbuscar.setBorder(null);
        jbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuscarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbuscarMouseReleased(evt);
            }
        });
        add(jbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 10));

        search.setBackground(new java.awt.Color(18, 90, 173));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Buscar");
        jLabel4.setToolTipText("Buscar Camión");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        search.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 80, 30));

        search1.setBackground(new java.awt.Color(18, 90, 173));
        search1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                search1MousePressed(evt);
            }
        });
        search1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Exportar");
        jLabel5.setToolTipText("Exportar Camiones");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        search1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 30));
    }// </editor-fold>//GEN-END:initComponents
 public void ocultarColumnas(JTable tbl, int columna) {
        // for (int i = 0; i< columna.length;i++) {
        tbl.getColumnModel().getColumn(columna).setMaxWidth(0);
        tbl.getColumnModel().getColumn(columna).setMinWidth(0);
        tbl.getTableHeader().getColumnModel().getColumn(columna).setMaxWidth(0);
        tbl.getTableHeader().getColumnModel().getColumn(columna).setMinWidth(0);
        //}
    }
    private void tablaCamionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCamionesMousePressed
        /* if(usrnm.getText().equals("") || usrnm.getText() == null || usrnm.getText().equals(" "))
        usrnm.setText("Ingrese el nombre de usuario a buscar");*/
    }//GEN-LAST:event_tablaCamionesMousePressed

    private void jchoferMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchoferMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchoferMousePressed

    private void jchoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchoferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchoferActionPerformed

    private void jmodeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmodeloMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmodeloMousePressed

    private void jmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmodeloActionPerformed

    private void jchapaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchapaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchapaMousePressed

    private void jchapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchapaActionPerformed

    private void btn_AddCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddCamionMouseEntered

    }//GEN-LAST:event_btn_AddCamionMouseEntered

    private void btn_AddCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddCamionMouseExited

    }//GEN-LAST:event_btn_AddCamionMouseExited

    private void btn_AddCamionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddCamionMousePressed
        String txtchapa = jchapa.getText();
        String txtmodelo = jmodelo.getText();
        String txtchofer = jchofer.getText();
        if (txtchapa.equals("") || txtmodelo.equals("") || txtchofer.equals("")) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (txtchapa.length() != 7 || !txtchapa.startsWith("E")) {
            JOptionPane.showMessageDialog(null, "Chapa incorrecta", "ERROR", JOptionPane.ERROR_MESSAGE);

        } else {
            cc.insertarCamiones(txtchapa, txtmodelo, txtchofer);
            cc.mostrarCamiones(tablaCamiones);
            ocultarColumnas(tablaCamiones, 0);
            jchapa.setText("");
            jmodelo.setText("");
            jchofer.setText("");
            /**
             * id serial primary key not null
             */
        }
    }//GEN-LAST:event_btn_AddCamionMousePressed

    private void panelAddCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddCamionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAddCamionMouseEntered

    private void panelAddCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddCamionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAddCamionMouseExited

    private void panelAddCamionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddCamionMousePressed

    }//GEN-LAST:event_panelAddCamionMousePressed

    private void btn_DelCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DelCamionMouseEntered

    }//GEN-LAST:event_btn_DelCamionMouseEntered

    private void btn_DelCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DelCamionMouseExited

    }//GEN-LAST:event_btn_DelCamionMouseExited

    private void btn_DelCamionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DelCamionMousePressed
        try {
            int idFila = tablaCamiones.getSelectedRow();
            String valorFilaID = String.valueOf(tablaCamiones.getValueAt(idFila, 0));
            if (idFila <= -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el camión a borrar. \n", "ADVERTENCIA", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                cc.eliminarCamion(valorFilaID);
                cc.mostrarCamiones(tablaCamiones);
                ocultarColumnas(tablaCamiones, 0);
                btn_DelCamion.setEnabled(false);
                btn_UpdateCamion.setEnabled(false);
                jchapa.setText("");
                jmodelo.setText("");
                jchofer.setText("");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_DelCamionMousePressed

    private void panelDelCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDelCamionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDelCamionMouseEntered

    private void panelDelCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDelCamionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDelCamionMouseExited

    private void panelDelCamionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDelCamionMousePressed

    }//GEN-LAST:event_panelDelCamionMousePressed

    private void btn_UpdateCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateCamionMouseEntered

    }//GEN-LAST:event_btn_UpdateCamionMouseEntered

    private void btn_UpdateCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateCamionMouseExited

    }//GEN-LAST:event_btn_UpdateCamionMouseExited

    private void btn_UpdateCamionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateCamionMousePressed
        String txtchapa = jchapa.getText();
        String txtmodelo = jmodelo.getText();
        String txtchofer = jchofer.getText();
        try {
            int idFila = tablaCamiones.getSelectedRow();
            String valorFilaID = String.valueOf(tablaCamiones.getValueAt(idFila, 0));

            if (idFila <= -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el camión a borrar. \n", "ADVERTENCIA", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                cc.editarCamion(valorFilaID, txtchapa, txtmodelo, txtchofer);
                cc.mostrarCamiones(tablaCamiones);
                ocultarColumnas(tablaCamiones, 0);
                btn_DelCamion.setEnabled(false);
                btn_UpdateCamion.setEnabled(false);
                btn_AddCamion.setEnabled(true);
                jchapa.setText("");
                jmodelo.setText("");
                jchofer.setText("");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btn_UpdateCamionMousePressed

    private void panelUpdateCamionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpdateCamionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUpdateCamionMouseEntered

    private void panelUpdateCamionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpdateCamionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUpdateCamionMouseExited

    private void panelUpdateCamionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpdateCamionMousePressed

    }//GEN-LAST:event_panelUpdateCamionMousePressed

    private void tablaCamionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCamionesMouseClicked
        btn_AddCamion.setEnabled(false);
        int idFila = tablaCamiones.getSelectedRow();
        String valorFilaID = String.valueOf(tablaCamiones.getValueAt(idFila, 0));
        String valorChapa = String.valueOf(tablaCamiones.getValueAt(idFila, 1));
        String valorModelo = String.valueOf(tablaCamiones.getValueAt(idFila, 2));
        String valorChofer = String.valueOf(tablaCamiones.getValueAt(idFila, 3));

        if (valorFilaID.equals("null")) {
            JOptionPane.showMessageDialog(null, "Fila Vacia", "AVISO",
                    JOptionPane.WARNING_MESSAGE);

        } else {
            jchapa.setText("");
            jmodelo.setText("");
            jchofer.setText("");
            jchapa.setText(valorChapa);
            jmodelo.setText(valorModelo);
            jchofer.setText(valorChofer);
            btn_DelCamion.setEnabled(true);
            btn_UpdateCamion.setEnabled(true);
        }

    }//GEN-LAST:event_tablaCamionesMouseClicked

    private void jbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscarMousePressed
        if (jbuscar.getText().equals("Ingrese el nombre de usuario a buscar"))
            jbuscar.setText("");
    }//GEN-LAST:event_jbuscarMousePressed

    private void jbuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscarMouseReleased
        //nothing
    }//GEN-LAST:event_jbuscarMouseReleased

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseExited

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed

    }//GEN-LAST:event_searchMousePressed

    private void search1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search1MouseEntered

    private void search1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search1MouseExited

    private void search1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MousePressed

    }//GEN-LAST:event_search1MousePressed

    private void jbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscarMouseClicked
        jbuscar.setText("");
    }//GEN-LAST:event_jbuscarMouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        if (jbuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (jbuscar.getText().length() != 7) {
            JOptionPane.showMessageDialog(null, "Intruduzca una Chapa Correcta", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            cc.buscarCamion(jbuscar.getText(), tablaCamiones);
            ocultarColumnas(tablaCamiones, 0);
        }
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        if (tablaCamiones.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No hay datos en la tabla para exportar", "ERROR", JOptionPane.ERROR_MESSAGE);

        } else {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<>();
                List<String> nom = new ArrayList<>();
                tb.add(tablaCamiones);
                nom.add("Detalle de Camiones");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exportar e = new Exportar(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel.", "AVISO",
                                JOptionPane.INFORMATION_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Hubo un error" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void jchoferKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchoferKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;

        if (!(minusculas || mayusculas || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_jchoferKeyTyped

    private void jchapaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchapaKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros || mayusculas)) {
            evt.consume();
        }

        if (jchapa.getText().trim().length() == 7) {
            evt.consume();
        }
    }//GEN-LAST:event_jchapaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel btn_AddCamion;
    private javax.swing.JLabel btn_DelCamion;
    private javax.swing.JLabel btn_UpdateCamion;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jbuscar;
    private javax.swing.JTextField jchapa;
    private javax.swing.JTextField jchofer;
    private javax.swing.JTextField jmodelo;
    private javax.swing.JPanel panelAddCamion;
    private javax.swing.JPanel panelDelCamion;
    private javax.swing.JPanel panelUpdateCamion;
    private javax.swing.JPanel search;
    private javax.swing.JPanel search1;
    private javax.swing.JTable tablaCamiones;
    // End of variables declaration//GEN-END:variables
}
