/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import sql.BaseDatos;
import java.awt.Component;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Esteban Ramos Martínez
 */
public class Configuracion extends javax.swing.JPanel {

    static String strhostname, strpuerto, strbasedatos, strusuario, strcontrasena, strsegundo, strdatos, strparada;
    Configuraciones config = new Configuraciones();

    /**
     * Creates new form Configuracion
     */
    public Configuracion() throws IOException {
        initComponents();
        ArrayList<String> arr = config.leerArchivo();
        hostname.setText(arr.get(0));
        puerto.setText(arr.get(1));
        namedb.setText(arr.get(2));
        usuariodb.setText(arr.get(3));
        passworddb.setText(arr.get(4));
        ArrayList<String> arrPserial = config.leerConfSerial();
        jComboBitsxsegundo.setSelectedItem(arrPserial.get(0));
        jComboBitsdeDatos.setSelectedItem(arrPserial.get(1));
        jComboBitsdeparada.setSelectedItem(arrPserial.get(2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        Title = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        hostname = new javax.swing.JTextField();
        Text3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        namedb = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        usuariodb = new javax.swing.JTextField();
        Text5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        btnGuardarCambios = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jComboBitsxsegundo = new javax.swing.JComboBox<>();
        jComboBitsdeDatos = new javax.swing.JComboBox<>();
        Text8 = new javax.swing.JLabel();
        jComboBitsdeparada = new javax.swing.JComboBox<>();
        Text9 = new javax.swing.JLabel();
        btnModificarpuerto = new javax.swing.JButton();
        btnGuardarCambiospuertos = new javax.swing.JButton();
        puerto = new javax.swing.JTextField();
        passworddb = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 465));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 10, 370));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Configuración Base Datos y Puerto de Comunicación");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 590, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Bits por segundo");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Hostname");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        hostname.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        hostname.setForeground(new java.awt.Color(102, 102, 102));
        hostname.setBorder(null);
        hostname.setEnabled(false);
        hostname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hostnameMousePressed(evt);
            }
        });
        hostname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostnameActionPerformed(evt);
            }
        });
        add(hostname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 30));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Puerto");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 10));

        namedb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        namedb.setForeground(new java.awt.Color(102, 102, 102));
        namedb.setBorder(null);
        namedb.setEnabled(false);
        namedb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                namedbMousePressed(evt);
            }
        });
        namedb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namedbActionPerformed(evt);
            }
        });
        add(namedb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 30));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Nombre de Base de Datos");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 10));

        usuariodb.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usuariodb.setForeground(new java.awt.Color(102, 102, 102));
        usuariodb.setBorder(null);
        usuariodb.setEnabled(false);
        usuariodb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuariodbMousePressed(evt);
            }
        });
        usuariodb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariodbActionPerformed(evt);
            }
        });
        add(usuariodb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 30));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Usuario");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Contraseña");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 260, 10));

        btnGuardarCambios.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar_cambios.png"))); // NOI18N
        btnGuardarCambios.setToolTipText("Guardar Cambios");
        btnGuardarCambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCambios.setEnabled(false);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 60, 50));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_conf.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 60, 50));

        jComboBitsxsegundo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "300", "1200", "2400", "4800", "9600", "19200", "38400", "57600", "115200", "230400", "460800", "921600" }));
        jComboBitsxsegundo.setBorder(null);
        jComboBitsxsegundo.setEnabled(false);
        jComboBitsxsegundo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBitsxsegundoItemStateChanged(evt);
            }
        });
        add(jComboBitsxsegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 200, -1));

        jComboBitsdeDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8" }));
        jComboBitsdeDatos.setSelectedIndex(3);
        jComboBitsdeDatos.setEnabled(false);
        jComboBitsdeDatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBitsdeDatosItemStateChanged(evt);
            }
        });
        add(jComboBitsdeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 200, -1));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Bits de Datos");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 110, -1));

        jComboBitsdeparada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2" }));
        jComboBitsdeparada.setEnabled(false);
        jComboBitsdeparada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBitsdeparadaItemStateChanged(evt);
            }
        });
        add(jComboBitsdeparada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 200, -1));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Bits de parada");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 110, -1));

        btnModificarpuerto.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarpuerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar_conf.png"))); // NOI18N
        btnModificarpuerto.setToolTipText("Modificar");
        btnModificarpuerto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarpuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarpuertoActionPerformed(evt);
            }
        });
        add(btnModificarpuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 60, 50));

        btnGuardarCambiospuertos.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardarCambiospuertos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar_cambios.png"))); // NOI18N
        btnGuardarCambiospuertos.setToolTipText("Guardar Cambios");
        btnGuardarCambiospuertos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarCambiospuertos.setEnabled(false);
        btnGuardarCambiospuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiospuertosActionPerformed(evt);
            }
        });
        add(btnGuardarCambiospuertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 60, 50));

        puerto.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        puerto.setForeground(new java.awt.Color(102, 102, 102));
        puerto.setBorder(null);
        puerto.setEnabled(false);
        puerto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                puertoMousePressed(evt);
            }
        });
        puerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puertoActionPerformed(evt);
            }
        });
        add(puerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 30));

        passworddb.setBorder(null);
        passworddb.setEnabled(false);
        passworddb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passworddbActionPerformed(evt);
            }
        });
        add(passworddb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 332, 260, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void hostnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostnameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostnameMousePressed

    private void hostnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostnameActionPerformed

    private void namedbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namedbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_namedbMousePressed

    private void namedbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namedbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namedbActionPerformed

    private void usuariodbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariodbMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariodbMousePressed

    private void usuariodbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariodbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariodbActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        hostname.setEnabled(true);
        puerto.setEnabled(true);
        namedb.setEnabled(true);
        usuariodb.setEnabled(true);
        passworddb.setEnabled(true);
        btnGuardarCambios.setEnabled(true);
        btnModificar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        strhostname = hostname.getText();
        strpuerto = puerto.getText();
        strbasedatos = namedb.getText();
        strusuario = usuariodb.getText();
        strcontrasena = passworddb.getText();
        if (strhostname.equals("") || strpuerto.equals("") || strbasedatos.equals("") || strusuario.equals("") || strcontrasena.equals("")) {
            Component rootPane = null;
            JOptionPane.showMessageDialog(rootPane, "No puede dejar campos vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean validconxion = new BaseDatos().conectarBD(strhostname, strpuerto, strbasedatos, strusuario, strcontrasena);
            if (validconxion) {

                btnGuardarCambios.setEnabled(false);
                btnModificar.setEnabled(true);
                hostname.setEnabled(false);
                puerto.setEnabled(false);
                namedb.setEnabled(false);
                usuariodb.setEnabled(false);
                passworddb.setEnabled(false);
                try {
                    config.editarArchivo(strhostname, strpuerto, strbasedatos, strusuario, strcontrasena);
                } catch (IOException ex) {
                    Logger.getLogger(BaseDatos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnModificarpuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarpuertoActionPerformed
        btnGuardarCambiospuertos.setEnabled(true);
        jComboBitsxsegundo.setEnabled(true);
        jComboBitsdeDatos.setEnabled(true);
        jComboBitsdeparada.setEnabled(true);
        btnModificarpuerto.setEnabled(false);
    }//GEN-LAST:event_btnModificarpuertoActionPerformed

    private void btnGuardarCambiospuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiospuertosActionPerformed
        Component rootPane = null;
        strsegundo = jComboBitsxsegundo.getSelectedItem().toString();
        strbasedatos = jComboBitsdeDatos.getSelectedItem().toString();
        strparada = jComboBitsdeparada.getSelectedItem().toString();
        try {
            config.editarConfSerial(strsegundo, strdatos, strparada);
            jComboBitsxsegundo.setEnabled(false);
            jComboBitsdeDatos.setEnabled(false);
            jComboBitsdeparada.setEnabled(false);
            btnModificarpuerto.setEnabled(true);
            btnGuardarCambiospuertos.setEnabled(false);
            JOptionPane.showMessageDialog(rootPane, "Cambios Guardados", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {

        }

       

    }//GEN-LAST:event_btnGuardarCambiospuertosActionPerformed

    private void jComboBitsxsegundoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBitsxsegundoItemStateChanged
        // strsegundo="";

    }//GEN-LAST:event_jComboBitsxsegundoItemStateChanged

    private void jComboBitsdeDatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBitsdeDatosItemStateChanged
        //  strbasedatos="";

    }//GEN-LAST:event_jComboBitsdeDatosItemStateChanged

    private void jComboBitsdeparadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBitsdeparadaItemStateChanged
        // strparada="";

    }//GEN-LAST:event_jComboBitsdeparadaItemStateChanged

    private void puertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puertoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoMousePressed

    private void puertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puertoActionPerformed

    private void passworddbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passworddbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passworddbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnGuardarCambiospuertos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarpuerto;
    private javax.swing.JTextField hostname;
    private javax.swing.JComboBox<String> jComboBitsdeDatos;
    private javax.swing.JComboBox<String> jComboBitsdeparada;
    private javax.swing.JComboBox<String> jComboBitsxsegundo;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField namedb;
    private javax.swing.JPasswordField passworddb;
    private javax.swing.JTextField puerto;
    private javax.swing.JTextField usuariodb;
    // End of variables declaration//GEN-END:variables
}
