/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Esteban Ramos Martínez
 */
public class Insert_zafras extends javax.swing.JPanel {

    /**
     * Creates new form Insert_zafras
     */
    public Insert_zafras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlan = new javax.swing.JTextField();
        Text5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlan.setForeground(new java.awt.Color(102, 102, 102));
        jPlan.setBorder(null);
        jPlan.setEnabled(false);
        jPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPlanMousePressed(evt);
            }
        });
        jPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlanActionPerformed(evt);
            }
        });
        add(jPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 260, 30));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Fecha Inicio");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Plan");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Fecha Fin");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jPlanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanMousePressed

    private void jPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JTextField jPlan;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
