/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import java.util.List;
import java.awt.Color;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import sql.CrudZafras;

/**
 *
 * @author Esteban Ramos Martínez
 */
public class Zafras extends javax.swing.JPanel {

    CrudZafras cz = new CrudZafras();

    /**
     * Creates new form Zafras
     */
    public Zafras() {
        initComponents();

        cz.mostrarZafras(tablaZafras);
        ocultarColumnas(tablaZafras, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaZafras = new javax.swing.JTable();
        panelBorrarZafra = new javax.swing.JPanel();
        btn_BorrarZafra = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        jPlan = new javax.swing.JTextField();
        Text5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        panelAddZafra = new javax.swing.JPanel();
        btn_AddZafra = new javax.swing.JLabel();
        search1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jbuscar = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        search = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaZafras.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tablaZafras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha Inicio", "Fecha Fin", "Año", "Plan", "Total Camiones", "Total Caña", "%"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaZafras.getTableHeader().setReorderingAllowed(false);
        tablaZafras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaZafrasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaZafras);
        if (tablaZafras.getColumnModel().getColumnCount() > 0) {
            tablaZafras.getColumnModel().getColumn(0).setResizable(false);
            tablaZafras.getColumnModel().getColumn(1).setResizable(false);
            tablaZafras.getColumnModel().getColumn(2).setResizable(false);
            tablaZafras.getColumnModel().getColumn(3).setResizable(false);
            tablaZafras.getColumnModel().getColumn(4).setResizable(false);
            tablaZafras.getColumnModel().getColumn(5).setResizable(false);
            tablaZafras.getColumnModel().getColumn(6).setResizable(false);
            tablaZafras.getColumnModel().getColumn(7).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 750, 180));

        panelBorrarZafra.setBackground(new java.awt.Color(18, 90, 173));
        panelBorrarZafra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBorrarZafra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelBorrarZafraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelBorrarZafraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBorrarZafraMousePressed(evt);
            }
        });
        panelBorrarZafra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_BorrarZafra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_BorrarZafra.setForeground(new java.awt.Color(255, 255, 255));
        btn_BorrarZafra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_BorrarZafra.setText("Borrar");
        btn_BorrarZafra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BorrarZafraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BorrarZafraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_BorrarZafraMousePressed(evt);
            }
        });
        panelBorrarZafra.add(btn_BorrarZafra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        add(panelBorrarZafra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 90, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Fecha Fin");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 80, -1));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Fecha Inicio");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, -1));

        jPlan.setForeground(new java.awt.Color(102, 102, 102));
        jPlan.setBorder(null);
        jPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPlanMousePressed(evt);
            }
        });
        jPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlanActionPerformed(evt);
            }
        });
        add(jPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 220, 30));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Plan");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 220, 10));

        panelAddZafra.setBackground(new java.awt.Color(18, 90, 173));
        panelAddZafra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelAddZafra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAddZafraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAddZafraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAddZafraMousePressed(evt);
            }
        });
        panelAddZafra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_AddZafra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_AddZafra.setForeground(new java.awt.Color(255, 255, 255));
        btn_AddZafra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_AddZafra.setText("Agregar");
        btn_AddZafra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AddZafraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AddZafraMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AddZafraMousePressed(evt);
            }
        });
        panelAddZafra.add(btn_AddZafra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        add(panelAddZafra, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 90, -1));

        search1.setBackground(new java.awt.Color(18, 90, 173));
        search1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                search1MousePressed(evt);
            }
        });
        search1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Exportar");
        jLabel5.setToolTipText("Exportar Camiones");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        search1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 30));

        jbuscar.setForeground(new java.awt.Color(102, 102, 102));
        jbuscar.setText("Ingrese el año de la zafra a buscar");
        jbuscar.setBorder(null);
        jbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuscarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jbuscarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbuscarMouseReleased(evt);
            }
        });
        add(jbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 10));

        search.setBackground(new java.awt.Color(18, 90, 173));
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchMousePressed(evt);
            }
        });
        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Buscar");
        jLabel4.setToolTipText("Buscar Camión");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        search.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    public void ocultarColumnas(JTable tbl, int columna) {
        // for (int i = 0; i< columna.length;i++) {
        tbl.getColumnModel().getColumn(columna).setMaxWidth(0);
        tbl.getColumnModel().getColumn(columna).setMinWidth(0);
        tbl.getTableHeader().getColumnModel().getColumn(columna).setMaxWidth(0);
        tbl.getTableHeader().getColumnModel().getColumn(columna).setMinWidth(0);
        //}
    }

    private void tablaZafrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaZafrasMousePressed
        /* if(usrnm.getText().equals("") || usrnm.getText() == null || usrnm.getText().equals(" "))
        usrnm.setText("Ingrese el nombre de usuario a buscar");*/
    }//GEN-LAST:event_tablaZafrasMousePressed

    private void btn_BorrarZafraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarZafraMousePressed
        try {
            int idFila = tablaZafras.getSelectedRow();
            String valorFilaID = String.valueOf(tablaZafras.getValueAt(idFila, 0));
            if (idFila <= -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar la zafra a borrar. \n", "ADVERTENCIA", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                cz.eliminar(valorFilaID);
                cz.mostrarZafras(tablaZafras);
                ocultarColumnas(tablaZafras, 0);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_BorrarZafraMousePressed

    private void panelBorrarZafraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorrarZafraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBorrarZafraMouseEntered

    private void panelBorrarZafraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorrarZafraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelBorrarZafraMouseExited

    private void panelBorrarZafraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBorrarZafraMousePressed

    }//GEN-LAST:event_panelBorrarZafraMousePressed

    private void jPlanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPlanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanMousePressed

    private void jPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlanActionPerformed

    private void btn_AddZafraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddZafraMousePressed

        if (jFechaInicio.toString().equals("") || jFechaFin.toString().equals("") || jPlan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat formatofechaAno = new SimpleDateFormat("yyyy");
            String strFechaInicial = formatofecha.format(jFechaInicio.getDate());
            String strFechaFin = formatofecha.format(jFechaFin.getDate());
            String ano = formatofechaAno.format(jFechaInicio.getDate());
            int year = Integer.parseInt(ano);
            Date finicio = null;
            Date ffin = null;
            try {
                finicio = formatofecha.parse(strFechaInicial);
                ffin = formatofecha.parse(strFechaFin);
            } catch (ParseException ex) {
                Logger.getLogger(Zafras.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (finicio.compareTo(ffin) > 0) {
                JOptionPane.showMessageDialog(null, "La Fecha de inicio no puede ser posterior que la fecha de fin", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (finicio.compareTo(ffin) == 0) {
                JOptionPane.showMessageDialog(null, "La Fechas no pueden ser iguales", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (cz.existeLaZafra(year) > 0) {
                JOptionPane.showMessageDialog(null, "Ya existe una zafra registrada en el " + ano, "ERROR", JOptionPane.ERROR_MESSAGE);

            } else {
                cz.insertarZafra(strFechaInicial, strFechaFin, jPlan.getText(), "0", "0", "0", ano);
                cz.mostrarZafras(tablaZafras);
                ocultarColumnas(tablaZafras, 0);
                jFechaInicio.setToolTipText("");
                jFechaFin.setToolTipText("");
                jPlan.setText("");
            }
        }
    }//GEN-LAST:event_btn_AddZafraMousePressed


    private void panelAddZafraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddZafraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAddZafraMouseEntered

    private void panelAddZafraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddZafraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAddZafraMouseExited

    private void panelAddZafraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAddZafraMousePressed

    }//GEN-LAST:event_panelAddZafraMousePressed

    private void btn_AddZafraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddZafraMouseEntered

    }//GEN-LAST:event_btn_AddZafraMouseEntered

    private void btn_AddZafraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AddZafraMouseExited

    }//GEN-LAST:event_btn_AddZafraMouseExited

    private void btn_BorrarZafraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarZafraMouseEntered

    }//GEN-LAST:event_btn_BorrarZafraMouseEntered

    private void btn_BorrarZafraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BorrarZafraMouseExited

    }//GEN-LAST:event_btn_BorrarZafraMouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        if (tablaZafras.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "No hay datos en la tabla para exportar", "ERROR", JOptionPane.ERROR_MESSAGE);

        } else {
            JFileChooser chooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel", "xls");
            chooser.setFileFilter(filter);
            chooser.setDialogTitle("Guardar archivo");
            chooser.setMultiSelectionEnabled(false);
            chooser.setAcceptAllFileFilterUsed(false);
            if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                List<JTable> tb = new ArrayList<>();
                List<String> nom = new ArrayList<>();
                tb.add(tablaZafras);
                nom.add("Detalle de Zafras");
                String file = chooser.getSelectedFile().toString().concat(".xls");
                try {
                    Exportar e = new Exportar(new File(file), tb, nom);
                    if (e.export()) {
                        JOptionPane.showMessageDialog(null, "Los datos fueron exportados a excel.", "AVISO",
                            JOptionPane.INFORMATION_MESSAGE);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Hubo un error" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void search1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search1MouseEntered

    private void search1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search1MouseExited

    private void search1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search1MousePressed

    }//GEN-LAST:event_search1MousePressed

    private void jbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscarMouseClicked
        jbuscar.setText("");
    }//GEN-LAST:event_jbuscarMouseClicked

    private void jbuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscarMousePressed
        if (jbuscar.getText().equals("Ingrese el nombre de usuario a buscar"))
        jbuscar.setText("");
    }//GEN-LAST:event_jbuscarMousePressed

    private void jbuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuscarMouseReleased
        //nothing
    }//GEN-LAST:event_jbuscarMouseReleased

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        if (jbuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (jbuscar.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "Intruduzca una Chapa Correcta", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
      /*      cc.buscarCamion(jbuscar.getText(), tablaCamiones);
            ocultarColumnas(tablaCamiones, 0);*/
        }
    }//GEN-LAST:event_jLabel4MousePressed

    private void searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseEntered

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseExited

    private void searchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMousePressed

    }//GEN-LAST:event_searchMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel btn_AddZafra;
    private javax.swing.JLabel btn_BorrarZafra;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jPlan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jbuscar;
    private javax.swing.JPanel panelAddZafra;
    private javax.swing.JPanel panelBorrarZafra;
    private javax.swing.JPanel search;
    private javax.swing.JPanel search1;
    private javax.swing.JTable tablaZafras;
    // End of variables declaration//GEN-END:variables
}
/*
CREATE TABLE IF NOT EXISTS public.zafras
(
    id_zafra bigint,
    fecha_inicio date,
    fecha_fin date,
    plan_cana integer,
    camiones_pesados integer,
    cana_pesada double precision,
    porcentaje_plan double precision,
    ano integer,
    CONSTRAINT za_pkey PRIMARY KEY (id_zafra)
)
 */
